#!/usr/bin/env python3
import sys
import json
import random
from urllib.request import urlopen
from urllib.error import HTTPError
from PIL import Image

verbose_mode = False

if len(sys.argv) == 1:
    print("usage: xkcd [-h] [--help]\n\t    [\"random\"] [\"latest\"] [COMIC_NUMBER]", file=sys.stderr)
    raise SystemExit(1)

def fetch_latest_json():
    with urlopen("https://xkcd.com/info.0.json") as req:
        return json.loads(req.read())

if sys.argv[1] == '-h' or sys.argv[1] == '--help':
    print(
        "usage: xkcd [-h] [--help]\n\t    [\"random\"] [\"latest\"] [COMIC_NUMBER]\n"
        "get xkcd comics, easy\n\n"
        "Arguments:\n\n"
        "\trandom\t\tget a random comic\n"
        "\tlatest\t\tget the latest comic\n"
        "\t[COMIC_NUMBER]\tget a specific comic, by number\n\n"
        "(c) 2022 nhtnr, released under the terms of the Unlicense\n"
        "For more information, please refer to <http://unlicense.org/>"
    )
    raise SystemExit(0)
elif sys.argv[1] == "latest":
    comic_number = fetch_latest_json()["num"]
elif sys.argv[1] == "random":
    comic_number = random.choice(
        list(
            range(1, fetch_latest_json()["num"]+1)
        )
    )
else:
    comic_number = sys.argv[1]

try:
    json_req = urlopen(f"https://xkcd.com/{comic_number}/info.0.json")
except HTTPError as e:
    if e.code == 404:
        print(f"xkcd: unable to find comic #{comic_number}", file=sys.stderr)
        raise SystemExit(1)
    else:
        print(f"An unknown HTTP error occurred! (HTTP {e.code})", file=sys.stderr)
        raise SystemExit(1)

comic_json = json.loads(json_req.read())
print(
    f"xkcd {comic_json['num']}: \"{comic_json['safe_title']}\" "
    f"({comic_json['month']}.{comic_json['day']}.{comic_json['year']})\n"
    f"{comic_json['alt']}"
)
img_link = comic_json["img"]
json_req.close()
img_req = urlopen(img_link)
with Image.open(img_req) as comic:
    comic.show()
